Fix the workflow

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -25,14 +25,26 @@ jobs:
           go-version: '1.23.1'
       - name: Build for Ouhissama (${{ matrix.os }} ${{ matrix.arch }})
         run: |
-          mkdir -p bin
+          platforms=("windows/amd64" "windows/arm64" "linux/amd64" "linux/arm64" "darwin/amd64" "darwin/arm64")
+      
+          for platform in "${platforms[@]}"; do
+            os_arch=(${platform//\// })
+            GOOS=${os_arch[0]}
+            GOARCH=${os_arch[1]}
 
           EXT=""
-          if [ "${{ matrix.os }}" == "windows" ]; then EXT=".exe"; fi
-          OUTPUT="ouhisama-${{ matrix.os }}-${{ matrix.arch }}${EXT}"
-
-          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/$OUTPUT cmd/ouhisama/ouhisama.go
-      - name: Check for changes
+          if [ "$GOOS" == "windows" ]; then EXT=".exe"; fi
+          OUTPUT="ouhisama-$GOOS-$GOARCH$EXT"
+        
+          echo "Building for $GOOS/$GOARCH"
+          GOOS=$GOOS GOARCH=$GOARCH go build -o bin/$OUTPUT .
+        
+          if [ $? -ne 0 ]; then
+            echo "Error occurred during building for $GOOS/$GOARCH"
+            exit 1
+          fi
+          done
+      - name: Check if there are any changes to commit
         id: check
         run: |
           if git diff --quiet; then
@@ -48,7 +60,7 @@ jobs:
             git config --local user.name "GitHub Actions"
             git config --local user.email "actions@github.com"
             git add bin/ouhisama
-            git commit -m "Build the Ouhi-sama program"
+            git commit -m "Build the Ouhi-sama programs"
             git push
         env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
